name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci --legacy-peer-deps

    - name: Install app dependencies
      run: npm ci --prefix apps/ng-test --legacy-peer-deps

    - name: Build application
      run: npm run build:github-pages

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      with:
        path: ./apps/ng-test/dist/ng-test/browser

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
